### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by choldawa** [choldawa/Practical-Ethics#1]
- [ ] Server side code
  - [ ] SONA
  - [ ] MTurk

- [ ] Trial sequencing (stops after x rounds)
- [ ] Multiple JSON data
- [ ] Move slider window (e.g. -.5 to 1.5 -> 0 to 2)
